import { Project } from "../types/types";

import PortfolioMockup from "/public/images/portfolio-new-mockup.png";
import WilfoMockup from "/public/images/wilfo-mockup.png";
import RevmatologenMockup from "/public/images/revmatologen-mockup.png";

// TODO: Refactor this into two different objects.
const projectData = {
  [Project.PORTFOLIONEW]: {
    title: "Portfolio 2.0",
    titleLong: "The second and updated version of my portfolio",
    description:
      "The second and updated version of my personal portfolio.\nA big leap forwards in terms of design, performance, and general usability.\nAbout, projects, contact and more.",
    descriptionLong:
      "Version 2.0 of my personal portfolio.\nI felt my first portfolio did not accurately represent my current skillset. I therefore created an updated version with a much better design and performance.\nIn addition, the source code itself is more modular and scalable, letting me easily update or extend the portfolio in the future.\nAll pages are statically generated at build time by Next.js.",
    date: "April 2022",
    tags: ["Next.js", "React", "TypeScript", "SCSS"],
    designTools: ["Figma"],
    gitHref: "https://github.com/maxvons/portfolio-2.0",
    href: "https://maxvons.dev",
    image: PortfolioMockup,
    images: [
      PortfolioMockup,
      PortfolioMockup,
      PortfolioMockup,
      PortfolioMockup,
      PortfolioMockup,
      PortfolioMockup,
    ],
    imageAlt: "A screenshot of Maximilian von Stephanides' new portfolio",
    imageAlts: [
      "A screenshot of Maximilian von Stephanides' new portfolio",
      "A screenshot of the mobile view of Maximilian von Stephanides' new portfolio",
      "A screenshot of the mobile view of Maximilian von Stephanides' new portfolio",
      "A screenshot of the mobile view of Maximilian von Stephanides' new portfolio",
      "A screenshot of the mobile view of Maximilian von Stephanides' new portfolio",
      "A screenshot of the mobile view of Maximilian von Stephanides' new portfolio",
    ],
    imageWidth: 1749,
    imageHeight: 1106,
    imageDimensions: [
      { width: 1749, height: 1106 },
      { width: 1749, height: 1106 },
      { width: 1749, height: 1106 },
      { width: 1749, height: 1106 },
      { width: 1749, height: 1106 },
      { width: 1749, height: 1106 },
    ],
  },
  [Project.WILFO]: {
    title: "What I've learned from others",
    titleLong: "What I've learned from others, my technical blog",
    description:
      "A concept and blog by Maximilian von Stephanides.\nA place where I post more or less technical articles, reviews, career tips, and more.\nAlso contains a growing collection of useful resources I've found over the years.",
    descriptionLong:
      "My personal concept and blog where I post more or less technical articles, reviews, career tips, and more.\nAt the start of my developer career, I was mainly reading and learning from others. Being inspired by these people, I wanted a place where I could share knowledge and useful content.\nWith this blog, I hope to educate and help others on their journey as beginning or senior developers, the way they have helped me in the past. I also post about whatever interests me at the time.",
    date: "May 2022",
    tags: ["Gatsby", "React", "TypeScript", "GraphQL", "SCSS"],
    designTools: ["Figma"],
    gitHref: "https://github.com/maxvons/blog",
    href: "https://github.com/maxvons/blog",
    image: WilfoMockup,
    images: [
      WilfoMockup,
      WilfoMockup,
      WilfoMockup,
      WilfoMockup,
      WilfoMockup,
      WilfoMockup,
    ],
    imageAlt:
      "A screenshot of Maximilian von Stephanides' blog, What I've Learned from Others",
    imageAlts: [
      "A screenshot of Maximilian von Stephanides' blog",
      "A screenshot of the mobile view of Maximilian von Stephanides' blog",
      "A screenshot of the mobile view of Maximilian von Stephanides' blog",
      "A screenshot of the mobile view of Maximilian von Stephanides' blog",
      "A screenshot of the mobile view of Maximilian von Stephanides' blog",
      "A screenshot of the mobile view of Maximilian von Stephanides' blog",
    ],
    imageWidth: 1695,
    imageHeight: 1245,
    imageDimensions: [
      { width: 1695, height: 1245 },
      { width: 1695, height: 1245 },
      { width: 1695, height: 1245 },
      { width: 1695, height: 1245 },
      { width: 1695, height: 1245 },
      { width: 1695, height: 1245 },
    ],
  },
  [Project.REVMATOLOGEN]: {
    title: "Dr. Signe von Stephanides",
    titleLong: "Homepage of Dr. Signe von Stephanides",
    description:
      "A homepage and digital presence for Dr. Signe von Stephanides.\nA project I worked on through my company, Decidable, where I was responsible for the design, and most of the development and maintenance of the website.\nThis was Decidable's first client project.",
    descriptionLong:
      "The homepage and digital presence of Dr. Signe von Stephanides.\nThis was my company's first paid client project. I was responsible for the design and most of the development of the website.\nThis was the first project where I had to communicate with and cater to a client's needs and wishes. It taught me a lot about using an agile approach and how to work with a client.",
    date: "May 2022",
    tags: ["Next.js", "React", "TypeScript", "SCSS"],
    designTools: ["Figma"],
    gitHref: "",
    href: "https://delightful-flower-009435a03.1.azurestaticapps.net/",
    image: RevmatologenMockup,
    images: [
      RevmatologenMockup,
      RevmatologenMockup,
      RevmatologenMockup,
      RevmatologenMockup,
      RevmatologenMockup,
      RevmatologenMockup,
    ],
    imageAlt: "Multiple screenshots of Dr. Signe von Stephanides' homepage",
    imageAlts: [
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
      "Multiple screenshots of Dr. Signe von Stephanides' homepage",
    ],
    imageWidth: 1774,
    imageHeight: 1292,
    imageDimensions: [
      { width: 1774, height: 1292 },
      { width: 1774, height: 1292 },
      { width: 1774, height: 1292 },
      { width: 1774, height: 1292 },
      { width: 1774, height: 1292 },
      { width: 1774, height: 1292 },
    ],
  },
  [Project.HAUGESUND]: {
    title: "Haugesund Øyelegesenter",
    titleLong: "",
    description:
      "A custom-built digital presence for the eye clinic, Haugesund Øyelegesenter.",
    descriptionLong: "",
    date: "",
    tags: ["HTML", "CSS", "JS", "localStorage"],
    designTools: [],
    gitHref: "https://github.com/maxvons/haugesund_oyelegesenter",
    href: "https://haugesundos.netlify.app/",
    image: "",
    images: [],
    imageAlt: "",
    imageAlts: [],
    imageWidth: 0,
    imageHeight: 0,
    imageDimensions: [],
  },
  [Project.CLEANLIST]: {
    title: "Clean List",
    titleLong: "",
    description: "A simple and clean to-do list for all your important tasks.",
    descriptionLong: "",
    date: "",
    tags: ["HTML", "CSS", "JS", "localStorage"],
    designTools: [],
    gitHref: "https://github.com/maxvons/CleanList",
    href: "https://www.cleanlist.dev/",
    image: "",
    images: [],
    imageAlt: "",
    imageAlts: [],
    imageWidth: 0,
    imageHeight: 0,
    imageDimensions: [],
  },
  [Project.PORTFOLIO]: {
    title: "Portfolio",
    titleLong: "",
    description:
      "The first digital product I created and published on the web. Made me hungry for more.",
    descriptionLong: "",
    date: "",
    tags: ["HTML", "CSS", "JS", "localStorage"],
    designTools: [],
    gitHref: "https://github.com/maxvons/portfolio",
    href: "https://www.maxvons.no/",
    image: "",
    images: [],
    imageAlt: "",
    imageAlts: [],
    imageWidth: 0,
    imageHeight: 0,
    imageDimensions: [],
  },
};

export { projectData };
